### ISSUE TITLE
Docker?

### ISSUE THREAD

**Issue by NeoMatrixJR** [dsoprea/youtube-autodownloader#2]
Any chance there's a docker for this and I'm just missing it?

**Comment by dsoprea** [comment]
There's really no benefit. Usage is just a couple of steps and the authentication aspect would always run outside of the image, which means you'd still have to install this project in order to access the helper scripts. 

1. The automatic-authentication workflow is one command that results in the auth-token being written to the right place on disk (I've added documentation for this, to help you). This works best in desktop environments and, alternatively, there are a couple of manual-auth scripts for console environments.
2. Use the playlist-search script to find the playlist ID.
3. Use the download script to sync all of the videos down.

That's it. (1) and (2) only have to be done once and (3) can easily be scheduled/scripted.

Let me know if I can be any further help. It's a useful tool.

**Comment by vincentcox** [comment]
Is the authentication part also needed for public playlists?
